### ISSUE TITLE
ProgramInformation writing throws exception

### ISSUE THREAD

**Issue by davemevans** [caststack/python-mpegdash#24]
Given the following manifest:
```
<?xml version="1.0" encoding="UTF-8"?>
<MPD type="static" xmlns="urn:mpeg:dash:schema:mpd:2011" profiles="urn:mpeg:dash:profile:isoff-live:2011" minBufferTime="PT0.451S" mediaPresentationDuration="PT0S">
<ProgramInformation>
	<Title>Test Title</Title>
	<Source>Test Source</Source>
</ProgramInformation>
<Period duration="PT0S" start="PT0S">
</Period>
</MPD>
```

calling `.write` throws the following exception:
```
Traceback (most recent call last):
  File "/mnt/c/work/python-mpegdash/tests/test_mpdtoxml.py", line 47, in test_pi
    MPEGDASHParser.write(mpd, './tests/mpd-samples/pi-output.mpd')
  File "/mnt/c/work/python-mpegdash/mpegdash/parser.py", line 41, in write
    cls.get_as_doc(mpd).writexml(f, indent='    ', addindent='    ', newl='\n')
  File "/mnt/c/work/python-mpegdash/mpegdash/parser.py", line 35, in get_as_doc
    write_child_node(xml_doc, 'MPD', mpd)
  File "/mnt/c/work/python-mpegdash/mpegdash/utils.py", line 61, in write_child_node
    node.write(new_elem)
  File "/mnt/c/work/python-mpegdash/mpegdash/nodes.py", line 732, in write
    write_child_node(xmlnode, 'ProgramInformation', self.program_informations)
  File "/mnt/c/work/python-mpegdash/mpegdash/utils.py", line 57, in write_child_node
    n.write(new_elem)
  File "/mnt/c/work/python-mpegdash/mpegdash/nodes.py", line 91, in write
    write_child_node(xmlnode, 'Source', self.sources)
  File "/mnt/c/work/python-mpegdash/mpegdash/utils.py", line 57, in write_child_node
    n.write(new_elem)
AttributeError: 'unicode' object has no attribute 'write'
```

Similar happens with user-created nodes except it fails with `'str' object` rather than `'unicode'`

**Comment by davemevans** [comment]
Fixed by #28.
